### ISSUE TITLE
vgg model

### ISSUE THREAD

**Issue by MuhammedNihaleey** [CDOTAD/SketchyDatabase#10]
No such file or directory: '/data1/zzl/model/caffe2torch/vgg_triplet_loss/photo/photo_vgg_190.pth'
This is the error i am encountering while running the feature_extract.py. I have already successfully run the train.py. i dont have a 'photo_vgg_190.pth' file and also the file location i need to change right?
can you give a solution

**Comment by CDOTAD** [comment]
I did not let the code make the directory if the path given did not exist. 

So You have to change the `--save_dir` with your own dir path, which already exists.

Your saving dir is at `t.save(photo_net.state_dict(), self.save_dir + '/photo' + '/photo_' + self.net + '_%s.pth' % epoch)`
