### ISSUE TITLE
models.TripletEmbedding and TripletNet Notfound

### ISSUE THREAD

**Issue by azikk** [CDOTAD/SketchyDatabase#2]
Hello I'm going to run the project
but when I come to **from models.TripletEmbedding import TripletNet**
I cant find the file
 
could you update it

**Comment by CDOTAD** [comment]
As it is a baseline model of my partner's paper, I'll release it until his paper has been released.

**Comment by xyy-Iv** [comment]
Is the TripletNetwork available now?

**Comment by CDOTAD** [comment]
> Is the TripletNetwork available now?

It is avaiable now
