### ISSUE TITLE
Something is fishy

### ISSUE THREAD

**Issue by ahmdtaha** [CDOTAD/SketchyDatabase#3]
I think this line leads to a bug
[sketch_name.find(fname) != -1:](https://github.com/CDOTAD/SketchyDatabase/blob/6955b0b11523a025321226e2152fcfa647b1feaa/data/triplet_input.py#L78)

For example if sketch_name = n03271574_3853-1.png while fname = n03271574_385, the python _find_ returns 0. However, this is a **different** image sharing the same prefix.

Proposed solution 
if sketch_name.split('-')[0] == fname:
.....

**Comment by CDOTAD** [comment]
Thank you for your correction! I'll fix it later.

**Comment by drcege** [comment]
You forgot to first remove the file extension (.png) of sketch_name.
Equality judgment fails if the file name does not contain any dashes.

**Comment by CDOTAD** [comment]
> You forgot to first remove the file extension (.png) of sketch_name.
> Equality judgment fails if the file name does not contain any dashes.

There is no image that does not cantion a dash in SketchyDatabase. Therefor, I do not remove the extension.
