### ISSUE TITLE
希望分享一下sketchy的数据集

### ISSUE THREAD

**Issue by AliceShen122** [CDOTAD/SketchyDatabase#4]
你好！可以麻烦您给我分享一下sketchy的数据集吗？我在那个官网上死活下载不下来，感谢万分！！！邮箱    1264696775@qq.com   真的很感谢～～～～

**Comment by CDOTAD** [comment]
这数据集有点大，不好靠邮箱发吧，你可以翻墙下一哈。

**Comment by AliceShen122** [comment]
今天晚上找有vpn的同学帮我下载了。谢谢你~还特意回复~





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CDOTAD"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月9日(星期四) 晚上9:30
收件人:&nbsp;"CDOTAD/SketchyDatabase"<SketchyDatabase@noreply.github.com&gt;;
抄送:&nbsp;"沈笑"<1264696775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CDOTAD/SketchyDatabase] 希望分享一下sketchy的数据集 (#4)




这数据集有点大，不好靠邮箱发吧，你可以翻墙下一哈。

**Comment by WestbrookZero** [comment]
@AliceShen122 可否百度网盘分享一下？翻墙也下载不了，要申请谷歌网盘权限。

**Comment by richlili** [comment]
> 今天晚上找有vpn的同学帮我下载了。谢谢你~还特意回复~
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人：&nbsp;”CDOTAD“<notifications@github.com>; 发送时间：&nbsp;2020年1月9日(星期四) 晚上9:30 收件人：&nbsp;”CDOTAD/SketchyDatabase“<SketchyDatabase@noreply.github.com>; 抄送：&nbsp;”沈笑“<1264696775@qq.com>;”作者“<author@noreply.github.com>; 主题：&nbsp;Re： [CDOTAD/SketchyDatabase] 希望分享一下sketchy的数据集 （#4） 这数据集有点大，不好靠邮箱发吧，你可以翻墙下一哈。 — 您收到此消息是因为您创作了该线程。 直接回复此邮件，在 GitHub 上查看，或取消订阅。

你好，能麻烦您分享一下吗，现在翻墙也不能下载了

**Comment by CDOTAD** [comment]
@richlili [https://drive.google.com/file/d/0B7ISyeE8QtDdTjE1MG9Gcy1kSkE/view?usp=sharing&resourcekey=0-r6nB4crmdU-LK7H38xnOUw](https://drive.google.com/file/d/0B7ISyeE8QtDdTjE1MG9Gcy1kSkE/view?usp=sharing&resourcekey=0-r6nB4crmdU-LK7H38xnOUw)
