### ISSUE TITLE
Image Augmentation

### ISSUE THREAD

**Issue by ahmdtaha** [CDOTAD/SketchyDatabase#5]
Can you please explain what is the point of the [following centercrop](https://github.com/CDOTAD/SketchyDatabase/blob/38235f73d50610dfdd2d54f8316b58dfc7f07348/data/triplet_input.py#L33)
If the image is already resized to 224, why center crop?

```
self.tranform = transforms.Compose([
            transforms.Resize(224),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
        ])
```

**Comment by CDOTAD** [comment]
Well, it's just a habit of mine.

**Comment by ahmdtaha** [comment]
Thanks for clarifying!
