### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by Janetalready** [CDOTAD/SketchyDatabase#7]
Hi! Could you please share the pre-trained model?

**Comment by CDOTAD** [comment]
The pre-trained models can be downloaded via this link [pre-trained models](https://drive.google.com/drive/folders/1S5pdA04H0TUVE9Mxznf3hXkdUmwBUbi8?usp=sharing)

**Comment by Janetalready** [comment]
Thanks! Could you please give me access to this google link?

**Comment by CDOTAD** [comment]
I have modified the link. You can try it again.

**Comment by Janetalready** [comment]
Thanks!
