### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by naoki7090624** [CDOTAD/SketchyDatabase#8]
It would be great if you can share a link to Sketchy Dataset.

**Comment by CDOTAD** [comment]
you can download it here, http://sketchy.eye.gatech.edu/

**Comment by naoki7090624** [comment]
I requested access to the Google Drive where the dataset is stored. Please give me access to the shared folder.

**Comment by WestbrookZero** [comment]
I have the same problem, could you please give me the download permission

**Comment by ccq195** [comment]
I requested access to the Google Drive where the dataset is stored. Could you please give me the download permission? Thanks.

**Comment by CDOTAD** [comment]
https://drive.google.com/file/d/0B7ISyeE8QtDdTjE1MG9Gcy1kSkE/view?usp=sharing&resourcekey=0-r6nB4crmdU-LK7H38xnOUw 
try this link

**Comment by skuley** [comment]
what is the difference b/w tx_000000000000 and tx_000100000000

**Comment by CDOTAD** [comment]
> 

see README in dataset

tx_000000000000 : image is non-uniformly scaled to 256x256
tx_000100000000 : image bounding box scaled to 256x256 with
                                   an additional +10% on each edge; note 
                                   that due to position within the image,
                                   sometimes the object is not centered
