### ISSUE TITLE
about pkl

### ISSUE THREAD

**Issue by MuhammedNihaleey** [CDOTAD/SketchyDatabase#9]
photo_data = pickle.load(open('feature/photo-resnet50_64-265.pkl', 'rb'))

where do i get this file.I have installed the dataset and there is no file with extension .pkl .

as i am having issue " No such file or directory: 'feature/photo-resnet50_64-265.pkl' "

**Comment by CDOTAD** [comment]
.pkl files are the extracted features of the testing dataset. 
You need to get it through the trained model.
You can refer to [feature_extract.py](https://github.com/CDOTAD/SketchyDatabase/blob/master/feature/feature_extract.py)
